"""
Programming Assignment 3 -- BONUS -- Scaling It Up
Worth up to +20 points on top of the 100-point Parts 1-3 assignment.
Optional. 

Name:
Collaborators:
Time spent:

--------------------------------------------------------------------------
THE TASK
--------------------------------------------------------------------------
1. Implement HeapERQueue below: the exact same public interface as the
   ERQueue you wrote in er_queue.py, but backed by Python's built-in
   heapq module instead of a plain list scan or shift.

2. Run both your ERQueue and this HeapERQueue through the synthetic event
   stream generated by generate_synthetic_events() (provided below, do not
   modify -- everyone should benchmark against the same data), timing each
   run with the time module.

3. Fill in benchmark() to print a small table comparing the two timings,
   then write 2-3 sentences (in the WRITE-UP section at the bottom of this
   docstring) on whether the gap matches what lecture would predict.

--------------------------------------------------------------------------
HINT
--------------------------------------------------------------------------
heapq is a MIN-heap over plain values or tuples. To keep
(esi_level, arrival_time, patient_id) ordered correctly -- and to break
ties by arrival time automatically -- think about what you push onto the
heap as a single comparable tuple, and in what order its fields belong.

--------------------------------------------------------------------------
SETUP
--------------------------------------------------------------------------
This file expects your completed er_queue.py (with a working ERQueue) to
sit in the same folder. It imports ERQueue from there for the comparison.

--------------------------------------------------------------------------
WRITE-UP  (fill this in after running benchmark())
--------------------------------------------------------------------------
    ERQueue timing:     ??? seconds
    HeapERQueue timing: ??? seconds

    (your 2-3 sentences here)

--------------------------------------------------------------------------
"""

import heapq
import random
import time

from er_queue import ERQueue


class HeapERQueue:
    """Same contract as ERQueue (see er_queue.py), backed by heapq."""

    def __init__(self):
        # TODO: pick your internal representation, e.g. self.heap = []
        ...

    def add_patient(self, patient_id, esi_level, arrival_time):
        # TODO
        ...

    def next_patient(self):
        """Raise IndexError if the queue is empty."""
        # TODO
        ...

    def peek_next(self):
        """Raise IndexError if the queue is empty."""
        # TODO
        ...

    def is_empty(self):
        # TODO
        ...

    def __len__(self):
        # TODO
        ...


def generate_synthetic_events(n, seed=42):
    """Provided -- do not modify.

    Generate a deterministic synthetic stream of n ARRIVE events with
    random ESI levels (1-5) and strictly increasing timestamps, followed
    by n TREAT events interleaved at the end so every patient eventually
    gets treated. Using a fixed seed means everyone benchmarks against
    the exact same data.
    """
    rng = random.Random(seed)
    events = []
    t = 0
    for i in range(n):
        t += rng.randint(1, 3)
        events.append((t, "ARRIVE", (f"P{i}", rng.randint(1, 5))))
    for _ in range(n):
        t += 1
        events.append((t, "TREAT", None))
    return events


def time_run(queue_factory, events):
    """Provided -- do not modify.

    Runs the same simulation loop used in er_queue.run_simulation, but
    inlined here so this file has no hard dependency on your Part 2 code
    (only on the ERQueue / HeapERQueue interface itself). Returns the
    elapsed wall-clock time in seconds.
    """
    queue = queue_factory()
    start = time.perf_counter()
    for timestamp, event_type, payload in events:
        if event_type == "ARRIVE":
            patient_id, esi_level = payload
            queue.add_patient(patient_id, esi_level, timestamp)
        elif event_type == "TREAT":
            if not queue.is_empty():
                queue.next_patient()
    return time.perf_counter() - start


def benchmark():
    """
    TODO: generate at least 20,000 synthetic events, time ERQueue and
    HeapERQueue on the identical event stream (use time_run + a lambda /
    factory for each queue type), and print a small comparison table,
    e.g.:

        implementation    time (s)
        ERQueue           ???
        HeapERQueue       ???
    """
    # TODO
    ...


if __name__ == "__main__":
    benchmark()
